services:
  identity-lynx:
    image: ahmedramseyshahin/identity-lynx:latest
    container_name: identity-lynx
    restart: unless-stopped
    env_file:
      - Lynx.IdentityService/.env
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - ConnectionStrings__MongoDB=mongodb://${USERS_DB_USERNAME}:${USERS_DB_PASSWORD}@users-db:27017
      - ConnectionStrings__RabbitMQ=amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    depends_on:
      - rabbitmq
      - users-db
      - redis
    ports:
      - "8080:8080"
    networks:
      - lynx-net
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - lynx-net
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  analytics-db:
    image: influxdb:2
    container_name: analytics-db
    ports:
      - "8086:8086"
    volumes:
      - analytics-db-data:/var/lib/influxdb2
      - analytics-db-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=lynx
      - DOCKER_INFLUXDB_INIT_BUCKET=lynx-bucket
      - DOCKER_INFLUXDB_INIT_USERNAME=${ANALYTICS_DB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ANALYTICS_DB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${ANALYTICS_DB_TOKEN}
    restart: unless-stopped
    networks:
      - lynx-net
  users-db:
    image: mongo:7.0
    container_name: users-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${USERS_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${USERS_DB_PASSWORD}
    volumes:
      - users-db-data:/data/db
    restart: unless-stopped
    networks:
       - lynx-net
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - lynx-net
    volumes:
      - redis-data:/data

volumes:
  analytics-db-data:
  analytics-db-config:
  users-db-data:
  rabbitmq-data:
  redis-data:

networks:
  lynx-net:
    driver: bridge
